stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw
    # params:
    #   - data_source.url

  pre_processing:
    cmd: python src/pre_processing.py
    deps:
      - src/pre_processing.py
      - data/raw
    outs:
      - data/interim

  feature_eng:
    cmd: python src/feature_eng.py
    deps:
      - src/feature_eng.py
      - data/interim
    outs:
      - data/processed
    # params:
    #   - feature_params

  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/processed
    outs:
      - models/model.pkl
    # params:
    #   - model_params

  model_evaluation:
    cmd: python src/model_eval.py
    deps:
      - src/model_eval.py
      - models/model.pkl
      
    metrics:
      - reports/metrics.json